const projectData = [
  {
    title: "Magic Mirror",
    category: "Development",
    image: "img/headshot.png",
    description: "I built a mirror that does stuff",
    slug: "magic-mirror",
    body: "this is the content of the article",
  },
  {
    title: "Weather Records",
    category: "Development",
    image: "img/headshot.png",
    description: "Today's hot! But is it hot relative to history?",
    slug: "weather-records",
    body: "this is the content of the article",
  },
  {
    title: "The Fly",
    category: "Climbing",
    image: "img/headshot.png",
    description: "I had this goal for like 20 years and then I did it",
    slug: "the-fly",
    body: "this is the content of the article",
  },
  {
    title: "Brother's Keeper",
    category: "Climbing",
    image: "img/headshot.png",
    description: "I had this goal for like 2 years and I'm still working on it",
    slug: "brothers-keeper",
    body: "this is the content of the article",
  },
  {
    title: "Ring Return",
    category: "Tinkering",
    image: "img/hook.png",
    description: "I have ",
    slug: "ring-return",
    body: "this is the content of the article",
  },
  {
    title: "Mac Stand",
    category: "Tinkering",
    image: "img/headshot.png",
    description: "I didn't want to pay $35 for a metal stand",
    slug: "mac-stand",
    body: "this is the content of the article",
  },
  {
    title: "Jaws II",
    category: "Climbing",
    image: "img/headshot.png",
    description: "Pulling off what I never thought I'd be capable of",
    slug: "jaws-ii",
    body: "this is the content of the article",
  },
  {
    title: "Confident Man Sit",
    category: "Climbing",
    image: "img/headshot.png",
    description: "A first ascent in a heavily-traveled area",
    slug: "confident-man-sit",
    body: "this is the content of the article",
  },
];

export default projectData;
